### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by stanier** [stanier/coyot.io#3]
As the repository is now public, I will start to track my progress with issues in hopes of better documentation and organization.

A list of features to be implemented can be found below.  **If you would like to contribute and are looking for a place to start, please feel free to pick up on any of these features**.

- [ ] Dashboard
    - [ ] Fix routing for dashboard as default view
    - [ ] Widget system for dashboard
- [ ] User Management
    - [ ] Ability to add/delete users
    - [ ] Role assignment
    - [ ] Sort by field
    - [ ] User groups
        - [ ] Group privileges and default attributes
- [ ] API/Plugin support
- [ ] Cluster/loadbalancing

Please feel free to suggest features that you would like to see added.
